#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $WHEELIE_HOME ]]; then
  echo "Error: WHEELIE_HOME not defined."
  exit 1
fi
if [[ ! -d $WHEELIE_HOME ]]; then
  echo "Error: directory not found: $WHEELIE_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

DHOME=$WHEELIE_HOME

. $DHOME/.dreleaserc

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
